describe('Navigation', () => {
  it('should navigate to the Contact page', () => {
    cy.viewport(1580, 820)
    cy.visit('http://localhost:3000')
    
    cy.scrollTo('0%', '45%', { duration: 2000 })
    cy.get('button').contains('React-js').click()
    cy.wait(2000)
    cy.get('button').contains('Vue-js').click()
    cy.wait(2000)
    cy.get('button').contains('React Native').click()
    cy.wait(2000)
    cy.get('button').contains('Aws').click()
    cy.wait(2000)
    cy.get('button').contains('Docker').click()
    cy.wait(1000)
    cy.get('button').contains('see details').click()
    cy.wait(1000)
    cy.get('.dialog').scrollTo('top')
    cy.get('.dialog').scrollTo('bottom', { duration: 3000 })
    cy.get('.close').click()
    cy.scrollTo('0%','92%', { duration: 3000 })
    cy.get('input[name="first-name"]').type('Daoudi')
    cy.get('input[name="last-name"]').type('Rachid')
    cy.get('input[name="email"]').type('rachiddaoudi@gmail.com')
    cy.get('label').contains('Development').click()
    cy.get('textarea[name="message"]').type('I am interested in your services and I would like to know more about your offers and prices')
    cy.get('button[name="send"]').click()
    cy.scrollTo('0%','0%', { duration: 3000 })
    cy.get('input[name="require offer"]').focus()
    cy.wait(1000)
    cy.get('input[name="require offer"]').type('rachiddaoudi@gmail.com')
    cy.get('button[name="require offer"]').click()
    
  })
})
